# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:
    if: github.repository == 'nkonev/r2dbc-migrate'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 17.0.4 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: |
          pwd
          ls -lah
          ./mvnw clean test -DenableOomTests=true
          rm -rf ~/.m2/repository/name/nkonev/r2dbc-migrate
